### ISSUE TITLE
"Cannot decode instruction for" error

### ISSUE THREAD

**Issue by ripoff2** [gagliardetto/solana-go#105]
Hey, I'm trying to understand why "pretty print" keeps failing for SOME of my instructions. For example, I added ComputeBudget program instructions and it works well. Also I added "SetCollectionDuringMint" instruction for metaplex candy machine but it keeps failing. It is funny because "MintNFT" instruction print well but the next instruction which is "SetCollectionDuringMint" got error: cannot decode instruction for cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ program: unable to decode instruction: no known type for type [103 17 200 25 118 95 125 61]". But the type is known, works and simply does not print well. Is there any specific to do with such things to properly decode new added instruction?

**Comment by gagliardetto** [comment]
hey, have you registered the decoder?

https://github.com/gagliardetto/solana-go/blob/3d8aa7fccde7cefdc0b9c870e190e766a372eb7c/programs/system/instructions.go#L42

**Comment by gagliardetto** [comment]
Each instruction also need to implement the `EncodeToTree` method:

https://github.com/gagliardetto/solana-go/blob/3d8aa7fccde7cefdc0b9c870e190e766a372eb7c/programs/system/CreateAccount.go#L133

**Comment by ripoff2** [comment]
@gagliardetto yes! This library provides lots of examples so I did this. I think it somehow connected with Anchor... When I was typing this answer I tried to make some changes and somehow it worked... (like I literally changed namings). Well, if it's possible I want to ask another question regarding instruction decoding. As u show in this example https://github.com/gagliardetto/solana-go/#parsedecode-an-instruction-from-a-transaction we can make a decoder for certain instruction and "pretty-print" it. But is it possible to gain values from instr params - in human readable version. For example, I wanna to get bump param from instruction and store it in a varuable.

**Comment by gagliardetto** [comment]
> I think it somehow connected with Anchor... When I was typing this answer I tried to make some changes and somehow it worked... (like I literally changed namings). 

Maybe the sighash was incorrect? In [`binary@v0.7.2`](https://github.com/gagliardetto/binary/releases/tag/v0.7.2), you can use `bin.SighashInstruction(name)` to get the instruction discriminant.

**Comment by gagliardetto** [comment]
> Well, if it's possible I want to ask another question regarding instruction decoding. As u show in this example https://github.com/gagliardetto/solana-go/#parsedecode-an-instruction-from-a-transaction we can make a decoder for certain instruction and "pretty-print" it. But is it possible to gain values from instr params - in human readable version. For example, I wanna to get bump param from instruction and store it in a varuable.

If you're talking about anchor, then yes, you can decode instruction params.

Something like this:

```go
dec := bin.NewBorshDecoder(data)

discriminant, err := dec.ReadBytes(8)
if err != nil {
	return nil, err
}

// check if discriminant is correct:
if !bytes.Equal(discriminant, bin.SighashInstruction("someInstruction")) {
	return nil, fmt.Errorf("invalid discriminant for instruction")
}

// read the rest of the data:
var instruction SomeInstruction
if err := dec.Decode(&instruction); err != nil {
	return nil, err
}
```

**Comment by ripoff2** [comment]
> Owner
Yes, everything is set. I did something like that and realized that I was getting memory address instead of value thats why I thought it did not work, anyway thank you for your hard work and help!
