### ISSUE TITLE
When will there be a v1.7.0 release?

### ISSUE THREAD

**Issue by bruce-riley** [gagliardetto/solana-go#111]
We are having issues with unmarshalling of V0 transactions failing on v1.6.0. The problem is resolved on the latest main, but we are leery about pinning to a specific commit. Is there an estimated date for the next release? If not, could a release be cut soon?

**Comment by gagliardetto** [comment]
Released; should use `[v1.7.1](https://github.com/gagliardetto/solana-go/releases/tag/v1.7.1)`

https://github.com/gagliardetto/solana-go/releases

`go get github.com/gagliardetto/solana-go@v1.7.1`

**Comment by gagliardetto** [comment]
There's not yet a client for the address lookup tables intructions.

**Comment by gagliardetto** [comment]
And there might still be some edge cases where v0 transaction unmarshaling fails.

**Comment by bruce-riley** [comment]
Thank you for the quick turn around. I'll keep an eye out for additional updates.
