### ISSUE TITLE
Pass string to msg!() in Custom solana program

### ISSUE THREAD

**Issue by Abhishek-Dojima** [gagliardetto/solana-go#114]
I want to call a method from my own custom solana program which takes a string as an Input and logs it in the transactions logs. 
I am implementing in this way: 
```go
	instructions := []solana.Instruction{
		&testTransactionInstructions{
			accounts: []*solana.AccountMeta{
				{PublicKey: fromaccount.PublicKey(), IsSigner: true, IsWritable: false},
				{PublicKey: toaccount.PublicKey(), IsSigner: true, IsWritable: true},
			},
			data:      []byte{0xaa, 0xbb},
			programID: progID,
		}}
	
	tx, err := solana.NewTransaction(instructions, recent.Value.Blockhash)
	
	sig, err := confirm.SendAndConfirmTransaction(
		context.TODO(),
		client,
		wsClient,
		tx,
	)
	if err != nil {
		panic(err)
	}
	spew.Dump(sig)
```
I am getting the error:
  panic: (*jsonrpc.RPCError)(0xc000364ed0)({
 Code: (int) -32602,
 Message: (string) (len=78) "invalid transaction: Transaction failed to sanitize accounts offsets correctly",
 Data: (interface {}) <nil>
})
What is incorrect here/correct way of calling custom programs?

**Comment by gagliardetto** [comment]
Try this:

https://github.com/gagliardetto/solana-go/blob/bbd443bc28d6e3ac665667ce154771ee18695745/generic_instruction_test.go#L24-L30

**Comment by Abhishek-Dojima** [comment]
That worked! Thanks.
