### ISSUE TITLE
Connection rate limits exceeded, contact your app developer or support@rpcpool.com.

### ISSUE THREAD

**Issue by JavinYang** [gagliardetto/solana-go#119]
I have requested SendAndConfirmTransaction for 100 times and reported the following error
```
         _, err = confirm.SendAndConfirmTransaction(
		context.TODO(),
		this.getRpcClient(),
		this.wsClient,
		tx,
	)
	if err != nil {
		panic(err)
	}
```

```
panic: (*jsonrpc.RPCError)(0x140001a1800)({
 Code: (int) 429,
 Message: (string) (len=83) "Connection rate limits exceeded, contact your app developer or support@rpcpool.com.",
 Data: (interface {}) <nil>
})
```

When I cut it down to 50 times, there's no problem
I want to know what the rpc limit is. Can I use higher concurrency?

**Comment by aspin** [comment]
This is dependent on your RPC provider and really related to this library at all

**Comment by gagliardetto** [comment]
For production apps, you should use a dedicated (paid) RPC node (and avoid the public solana RPC).

**Comment by shackra** [comment]
is there any way to respect the rate limiting of the provider anyway?
