### ISSUE TITLE
How to decode a raw transaction into a transaction object?

### ISSUE THREAD

**Issue by GCrispino** [gagliardetto/solana-go#15]
Hello,

I don't understand if it's possible to decode a raw transaction string to a solana.Transaction object in the SDK. I'd like to do this to support the feature of getting a raw transaction from a user and only submitting that to the network via the sendTransaction rpc method, which takes a transaction.

Maybe doing some borsh decoder like [here](https://github.com/gagliardetto/solana-go#borsh-encodingdecoding) could help, but don't really know.
Any tips?

Also, if there's the interest, there could exist a function in the rpc package to submit raw transaction strings directly, without the need to convert to a transaction, or provide a function that easily converts that, maybe in the transaction package (in the case that there doesn't exist one)

**Comment by Lazar955** [comment]
Hey there @gagliardetto, I have a similar question so I think I'll tag along on this PR.

When calling `TransactionFromDecoder` it returns the `solana.Transaction` type but when calling the RPC method `GetTransaction` it returns `rpc.GetTransactionResult`, is there a reason why the Transaction struct does not have the `meta` prop?

Also, how would a encode a transaction is there an example for this? 

Thanks

**Comment by gagliardetto** [comment]
Hi @Lazar955 

You're right, that's a bit of a clusterf*ck. Some things need to be removed. Will look into it today.

**Comment by gagliardetto** [comment]
`GetParsedTransaction` return the **json** representation of the transaction.

You need to call `GetBinary` instead:

https://github.com/gagliardetto/solana-go/blob/e256f25d879c68c549a16184937133685788b96c/rpc/examples/getTransaction/getTransaction.go#L70-L83

Something like this:

```go
	{
		out, err := client.GetTransaction(
			context.TODO(),
			txSig,
			&rpc.GetTransactionOpts{
				Encoding: solana.EncodingBase64,
			},
		)
		if err != nil {
			panic(err)
		}
		spew.Dump(out)
		spew.Dump(out.Transaction.GetBinary())

		decodedTx, err := solana.TransactionFromDecoder(bin.NewBinDecoder(out.Transaction.GetBinary()))
		if err != nil {
			panic(err)
		}
		spew.Dump(decodedTx)
	}
```

**Comment by gagliardetto** [comment]
@Lazar955

**Comment by Lazar955** [comment]
Thanks for the quick response @gagliardetto! Appreciate the effort that you have put into this project

**Comment by elvis-hp** [comment]
I have an error: cannot decode instruction for TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA program: instruction decoder not found

please help me.
tx: vfXRWpvaQWAg8DZ4eoKX3ngt6gifm12Lv1XbZ25sNJD888w8YBJw7LQ2kCP3dwUDC62kiThYELmLyzsBG6nQybt
