### ISSUE TITLE
Cannot build account meta during transaction decoding

### ISSUE THREAD

**Issue by matterai** [gagliardetto/solana-go#167]
Assume I have a code simply fetches a transaction. Then I take specific instruction and try to call `ResolveInstructionAccounts` method. It returns me an error: `cannot build account meta list without address tables`. 

Code running:
```golang
tx, err := rpcService.GetTransactionInfo(logEvent.Value.Signature)
if err != nil {
  return err
}

idoPurchase := tx.Message.Instructions[4]
accounts, err := idoPurchase.ResolveInstructionAccounts(&tx.Message) // Error returns here!
if err != nil {
  return err
}

inst, err := system.DecodeInstruction(accounts, idoPurchase.Data)
if err != nil {
  return err
}

spew.Dump(inst)
```

Transaction I fetch using code from [docs](https://github.com/gagliardetto/solana-go?tab=readme-ov-file#parsedecode-an-instruction-from-a-transaction). Code for fetching transaction looks like this:
```golang
func (s *SolanaRpcService) GetTransactionInfo(signature solana.Signature) (*solana.Transaction, error) {
	version := uint64(0)
	out, err := s.rpcClient.GetTransaction(
		context.Background(),
		signature,
		&rpc.GetTransactionOpts{
			Encoding:                       solana.EncodingBase64,
			MaxSupportedTransactionVersion: &version,
		},
	)
	if err != nil {
		return nil, err
	}

	tx, err := solana.TransactionFromDecoder(bin.NewBinDecoder(out.Transaction.GetBinary()))
	if err != nil {
		return nil, err
	}

	return tx, nil
}
```
I am not quite sure what am I doing wrong? Please, elaborate me or give me a reference to the doc part which I missed.

**Comment by gagliardetto** [comment]
You need to resolve the address table lookups first

https://github.com/gagliardetto/solana-go#address-lookup-tables
