### ISSUE TITLE
LogsSubscribeMentions accepts only one key, should array of keys

### ISSUE THREAD

**Issue by dot5enko** [gagliardetto/solana-go#17]
cannot override it in userspace as Client::logsSubscribe is private

**Comment by dot5enko** [comment]
oh, i see. its not working like expected. there is no possibility to subscribe for logs of multiple accounts in one call.

**Comment by gagliardetto** [comment]
yep, one key = one subscription

does not matter how many subscriptions you create, they all use the same underlying websocket.

**Comment by dot5enko** [comment]
@gagliardetto oh, thanks for clarification. thought it uses separate requests :) havent go that deep and verified in code
