### ISSUE TITLE
UiTokenAmount data type

### ISSUE THREAD

**Issue by lucasoares** [gagliardetto/solana-go#191]
What is the reason the `UiAmount *float64` is deprecated? I saw the blame information and apparently, the UiAmount was previously of the type `*bin.JSONFloat64`.

I don't know which field is reliable and when I should use each one of them... And if I use the string type, should I use a type from `bin` library to parse it?

**Comment by 0xvbetsun** [comment]
let's refer to the [documentation](https://solana.com/docs/rpc/http/gettokenaccountbalance) of solana RPC.

- `amount: <string>` - the raw balance without decimals, a string representation of `u64`
- `decimals: <u8>` - number of base 10 digits to the right of the decimal place
- `uiAmount: <number|null>` - the balance, using mint-prescribed decimals **DEPRECATED**
- `uiAmountString: <string>` - the balance as a string, using mint-prescribed decimals

I'd recommend parsing `amount` and using `decimals` for your internal calculations

to achieve this `bin` is not mandatory. Just use `stdlib`
```go
// to uint64
amnt, err := strconv.ParseUint(amount, 10, 64)

// or to *big.Int
amnt, ok := new(big.Int).SetString(amount, 10)
```
