### ISSUE TITLE
How to get a nonce from Account?

### ISSUE THREAD

**Issue by dn-l** [gagliardetto/solana-go#22]
JS library has this method https://github.com/solana-labs/solana-web3.js/blob/85bd523517683e1dbbb1d1e88116215dbd8a4678/src/nonce-account.ts#L55

Is there something similar in solana-go?

**Comment by gagliardetto** [comment]
Hi

I added the NonceAccount struct: https://github.com/gagliardetto/solana-go/blob/e5f3c23faee34d32d5d43c63e781acd150512791/programs/system/accounts.go#L24


You can see here an example usage:

https://github.com/gagliardetto/solana-go/blob/e5f3c23faee34d32d5d43c63e781acd150512791/programs/system/accounts_test.go#L27-L36

**Comment by dn-l** [comment]
@gagliardetto thank you!
