### ISSUE TITLE
how to transfer spl token to a new account with out funding???

### ISSUE THREAD

**Issue by BillInUK** [gagliardetto/solana-go#226]
when i transfer spl token to a new account,i must funding 0.002 sol to create a token account. how can i transfer spl token to a new account with out funding?

**Comment by SC4RECOIN** [comment]
this is more of a Solana question and not about the lib but you need to create an associated token account
https://github.com/gagliardetto/solana-go/blob/c7a7525bd05bdb366577b9fc7511cad60cfe5ba0/programs/associated-token-account/Create.go#L193

**Comment by BillInUK** [comment]
Thank you for your response. So, does that mean the gas fee for creating an account is unavoidable?
