### ISSUE TITLE
Nonce account usage

### ISSUE THREAD

**Issue by Lazar955** [gagliardetto/solana-go#23]
Hey there,

How would one go about:
1. Creating a nonce account
2. Getting the nonce value
3. Creating a tx with that nonce value instead of the recent block hash (I guess pass it instead of the block hash right?)

Thanks,

**Comment by gagliardetto** [comment]
Hi

I don't have an example of nonce account usage yet, but the nonce-relate instructions are part of the `system` programs; see https://github.com/gagliardetto/solana-go/tree/main/programs/system

You can take a look at Portto's examples; https://github.com/portto/solana-go-sdk/tree/main/examples/advanced/durable-nonce
