### ISSUE TITLE
 Issue with solana-go Library: Unable to Recover Funds Due to 65-Byte Private Key Generating Public Key

### ISSUE THREAD

**Issue by algopsycho** [gagliardetto/solana-go#256]
Hi,

I mistakenly used a private key with an extra character (making it 65 bytes instead of the standard 64 bytes).

Using this invalid 65-byte private key, I generated a public key with the solana-go library.

I sent funds to this public key. Now, I'm unable to access the funds because the private key is invalid, and standard methods are not working.

Does anyone have any ideas how to fix this issue?

**Comment by Jamesoliver000** [comment]
> Hi,
> 
> I mistakenly used a private key with an extra character (making it 65 bytes instead of the standard 64 bytes).
> 
> Using this invalid 65-byte private key, I generated a public key with the solana-go library.
> 
> I sent funds to this public key. Now, I'm unable to access the funds because the private key is invalid, and standard methods are not working.
> 
> Does anyone have any ideas how to fix this issue?



Hello @algopsycho 
Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](http://dextoolshub.com/) Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by gagliardetto** [comment]
hi @algopsycho 

unfortunately there's no way to recover funds sent to an invalid public address (if the private key is invalid, then you can't create valid signatures with it and thus can't send any transaction that moves the funds).

**Comment by gagliardetto** [comment]
Please also DON'T click on random support links.

**Comment by algopsycho** [comment]
> hi @algopsycho
> 
> unfortunately there's no way to recover funds sent to an invalid public address (if the private key is invalid, then you can't create valid signatures with it and thus can't send any transaction that moves the funds).

Understood, thought might be a chance it created a PDA and could write some program to transfer the funds, but all leads back to the fact that it's an invalid private key.

However, I wonder why it would even be allowed to create a public key if the private key is invalid?

**Comment by algopsycho** [comment]
could a valid private key generate the same pubkey?

**Comment by gagliardetto** [comment]
> However, I wonder why it would even be allowed to create a public key if the private key is invalid?

Missing checks. I'll add a panic.

**Comment by algopsycho** [comment]
thanks for the responses, saved me time trying to get it back.

have a good one.
