### ISSUE TITLE
GetRecentBlockhash error

### ISSUE THREAD

**Issue by zy166317** [gagliardetto/solana-go#257]
panic: (*jsonrpc.RPCError)(0xc00009ac90)({
 Code: (int) -32601,
 Message: (string) (len=16) "Method not found",
 Data: (interface {}) <nil>
})

**Comment by lphhh** [comment]
+1

**Comment by lphhh** [comment]
This method is expected to be removed in solana-core v2.0. Please use [getLatestBlockhash](https://solana.com/docs/rpc/http/getlatestblockhash) instead

**Comment by prdsrm** [comment]
Change your code to this:
```go
recent, err := rpcClient.GetLatestBlockhash(context.TODO(), rpc.CommitmentFinalized)
if err != nil {
	panic(err) // don't do this, handle the error yourself
}
```
Maybe the examples should be updated, no?
