### ISSUE TITLE
how to send sol from one address to another using this sdk?

### ISSUE THREAD

**Issue by simplewhale** [gagliardetto/solana-go#3]
how to send sol from one address to another using this sdk?

**Comment by gagliardetto** [comment]
I added an example here: https://github.com/gagliardetto/solana-go#transfer-sol-from-one-wallet-to-another-wallet

**Comment by simplewhale** [comment]
why didn't  I recieve the sol? 
https://explorer.solana.com/tx/5zcTcdJW7MU5Szt9HnwYXpaP7SAtHA7waCiG6LinCPYME3TGwv8J9m3vSeJZoLycGe93biFZ9N7YJhERVHjiMeyo

**Comment by simplewhale** [comment]
thank you for your demo. 
how about tokens?

**Comment by gagliardetto** [comment]
The client for the token program is not implemented yet.

Working on it.

**Comment by gagliardetto** [comment]
I'll release a client for the `token` program in the next few days after test driving it.

**Comment by simplewhale** [comment]
Wow, that would be great

**Comment by gagliardetto** [comment]
`token` program client release with `v0.4.4`; will add an example tomorrow.

**Comment by simplewhale** [comment]
okey

**Comment by gagliardetto** [comment]
The examples are gonna be a bit more complicated compared to a simple sol trasfer. Will try to do them in the next few days.
