### ISSUE TITLE
Default encoding for GetAccountInfoWithOpts

### ISSUE THREAD

**Issue by pikomonde** [gagliardetto/solana-go#31]
I tried to use `GetAccountInfoWithOpts`, I only need to change the `Commitment` option like this:
```
accountInfo, err := cli.rpcClient.GetAccountInfoWithOpts(
	context.Background(),
	accountPubKey,
	&rpc.GetAccountInfoOpts{
		Commitment: rpc.CommitmentConfirmed,
	},
)
```
but getting this error:
```
rpc.GetAccountInfoResult.Value: rpc.Account.Executable: Data: unmarshalerDecoder: Unknown kind: [34 74 110 114 80 57 34], error found in #10 byte of ...|a":"JnrP9","executab|..., bigger context ...|{"context":{"slot":395502},"value":{"data":"JnrP9","executable":false,"lamports":918720,"owner":"7te|...
```

I think the error is because I did not set the `Encoding` option. If I code like this, it works.
```
accountInfo, err := cli.rpcClient.GetAccountInfoWithOpts(
	context.Background(),
	accountPubKey,
	&rpc.GetAccountInfoOpts{
		Encoding: solana.EncodingBase64,
		Commitment: rpc.CommitmentConfirmed,
	},
)
```

I think, it's good to add something like default Encoding if the Encoding option is empty string. Something like this on `GetAccountInfoWithOpts`:
```
if opts.Encoding == "" {
	obj["encoding"] = solana.EncodingBase64
}
```

What do you think?

**Comment by gagliardetto** [comment]
> I think, it's good to add something like default Encoding if the Encoding option is empty string. Something like this on `GetAccountInfoWithOpts`:
> 
> ```
> if opts.Encoding == "" {
> 	obj["encoding"] = solana.EncodingBase64
> }
> ```
> 
> What do you think?

Yeah that would some issues and possible errors.

Keeping this issue as reminder.
