### ISSUE TITLE
Error when exporting to WASM

### ISSUE THREAD

**Issue by pikomonde** [gagliardetto/solana-go#35]
When I run this cli command to generate wasm binary:
`GOOS=js GOARCH=wasm go build -o output/html/aneka_guess_number/script/app.wasm cmd/html/aneka_guess_number/app.go`

I got this error:

```
vendor/github.com/fatih/color/color.go:21:5: undefined: isatty.IsTerminal
```

I tried to resolve this by bump up the version of `github.com/fatih/color`, from `v1.7.0` to `v1.9.0`. After bumping up the version, I can compile to WASM. I create the related PR to bump up the version. #34 

---
It's my first time creating PR to open source project, please correct me if there is mistake. Thanks!

**Comment by gagliardetto** [comment]
Thank you!

Merged #34
