### ISSUE TITLE
`blockSubscribe` feed doesn't work

### ISSUE THREAD

**Issue by aspin** [gagliardetto/solana-go#54]
Reference: https://docs.solana.com/developing/clients/jsonrpc-api#blocksubscribe---unstable-disabled-by-default

The docs are a bit ambiguous on this, probably be cause the endpoint is still considered unstable. In the endpoint description, it says the first parameter is `filter: <string>|<object>`, but the example indicates it should be `<string>|<object>`, like `{ "jsonrpc": "2.0", "id": "1", "method": "blockSubscribe", "params": ["all"] }`. This library implements the first, e.g. `"params": [{"filter": "all"}]`, which doesn't work.

**Comment by gagliardetto** [comment]
Thanks!
