### ISSUE TITLE
rpc.Client struct needs to implement a close method for its own socket

### ISSUE THREAD

**Issue by whymidnight** [gagliardetto/solana-go#77]
gm,

may be this is an edge case - whenever you instance many `rpc.New` calls, macOS would throw `tcp lookup not found` errors even after `ulimit -n 69420710` or `ulimit > unlimited`. so in my programs, i have to instance a global `rpc.Client` via `rpc.New` and then pass down to functions that require rpc interactions. this implies that many instances of `rpc.New` will exceed the OS max open sockets and fail due to not being closed after usage.

so i would like to know where to start on making the pr that implements this if you dont have time to. or i would be eternally grateful if this gets implemented in a future release.

much love <3,
D

**Comment by gagliardetto** [comment]
what's your use-case that requires throw-away clients?

**Comment by whymidnight** [comment]
at one point in the past, i had baked in anchor events and spawned goroutines that contained some logic with many rpc calls upon receiving the message over the rpc websocket. i wasnt sure if this was threadsafe at the time so it seemed more elegant to instead instance a new rpc struct inside the callback so that each goroutine had its own rpc client. however this didnt scale because of the above issue.

additionally, this approach of passing an `rpc.Client` pointer to functions that require does not allow for go modules to contain their own rpc lifecycle like - for instance: i have a utilities module for sending transactions, parsing chain state, etc; another module for my chain program; and some arbitrary third module.

if i wanted to import these modules in a disparate codebase, would require to also declare `rpc.New` in the main module which could be alleviated if the above modules could instance `rpc.New` themselves. however these modules must close their sockets to prevent the main module from exceeding open sockets.

**Comment by gagliardetto** [comment]
and you're doing the same thing with websocket clients?

**Comment by whymidnight** [comment]
well i can foresee this applying to websocket clients as well like awaiting for signature confirmations via ws in a confined thread inside the main thread.

**Comment by whymidnight** [comment]
however the http client design means that disparate modules are dependent on the main thread passing a pointer which isn't as elegant when modules could manage their own lifecycle of it. however is actually probably bad design in the bigger scheme of things since this means >1 `rpc.Client` versus 1 _global_ `rpc.Client`. as the issue of exceeding open sockets could still arise.

**Comment by gagliardetto** [comment]
the rpc client is made to be as efficient as possible (reusing TCP connections, enabling gzip compression, etc.)

if you don't want all of that, you'll waste time & resources reconnecting for each RPC call (maybe even having to make a DNS resolution).

**Comment by gagliardetto** [comment]
> for instance: i have a utilities module for sending transactions, parsing chain state, etc; another module for my chain program; and some arbitrary third module.

great! use 3 rpc clients :grin:

**Comment by whymidnight** [comment]
> if you don't want all of that, you'll waste time & resources reconnecting for each RPC call (maybe even having to make a DNS resolution).

thats exactly what i needed to hear. it took a discussion to realise this lol. thank you! i'll close this issue now.

much love,
D.
