### ISSUE TITLE
`rpcClient.SetHeader` not setting header

### ISSUE THREAD

**Issue by danthegoodman1** [gagliardetto/solana-go#85]
with some simple code like

```go
client := rpc.New(endpoint)
client.SetHeader("x-api-key", "...")
```

I can see from requests to something like webhook.site that subsequent RPC calls do not include the header:

body received:
```json
{
  "method": "getAccountInfo",
  "params": [
    "xxx",
    {
      "encoding": "base64"
    }
  ],
  "id": 0,
  "jsonrpc": "2.0"
}
```

<img width="355" alt="image" src="https://user-images.githubusercontent.com/17806508/177875803-8a8699e4-4d68-4ed6-a033-01aa1967ab7b.png">

**Comment by danthegoodman1** [comment]
Workaround is the following:

```go
	client := rpc.NewWithCustomRPCClient(jsonrpc.NewClientWithOpts(endpoint, &jsonrpc.RPCClientOpts{
		CustomHeaders: map[string]string{
			"x-api-key": "...",
		},
	}))
```

**Comment by gagliardetto** [comment]
yep! that was a piece that got lost.

I removed the dummy `SetHeader` method, and added `rpc.NewWithHeaders` that creates a new client with the specified headers: https://github.com/gagliardetto/solana-go/pull/89

(which is basically an alias for the workaround you posted above).
